services:
  web:
    image: portfolio:0.2.0
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`roshananand.cloud`)"
      - "traefik.http.routers.webapp.entrypoints=websecure"
      - "traefik.http.routers.webapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.webapp.loadbalancer.server.port=80"
    deploy:
      update_config:
        order: start-first
networks:
  proxy_net:
    external: true
