services:
  web:
    image: portfolio:0.2.5
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`roshananand.cloud`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=cloudflare"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.constraint-label=head-proxy"
    deploy:
      update_config:
        order: start-first
networks:
  proxy_net:
    external: true
