import type { Metadata } from "next";
import { Montserrat, PT_Sans, PT_Sans_Caption } from "next/font/google";
import "@/styles/globals.css";

const high = Montserrat({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-high",
  display: "swap",
});

const medium = PT_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-medium",
  display: "swap",
});

const small = PT_Sans_Caption({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-small",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${high.variable} ${medium.variable} ${small.variable} select-none`}>
        {children}
      </body>
    </html>
  );
}
